# Generated by Django 4.2.3 on 2023-07-16 08:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_user_friends_friendlyrequest'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='friends_Count',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='friendlyrequest',
            name='status',
            field=models.CharField(choices=[('accepted', 'accepted'), ('sent', 'sent'), ('rejected', 'rejected')], default='sent', max_length=20),
        ),
    ]
