# Generated by Django 4.2.3 on 2023-07-16 08:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_user_friends_count_alter_friendlyrequest_status'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='friends_Count',
            new_name='friends_count',
        ),
        migrations.AlterField(
            model_name='friendlyrequest',
            name='status',
            field=models.CharField(choices=[('sent', 'sent'), ('rejected', 'rejected'), ('accepted', 'accepted')], default='sent', max_length=20),
        ),
    ]
